---
title: "merging and apriori"
author: "Almog"
date: "24/09/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(knitr)
library(dplyr)
library(arules)
library(arulesViz)
```

## Merging
```{r}
courses <- read.csv("data/courses.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
assessments <-read.csv("data/assessments.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
studentassessment <- read.csv("data/studentAssessment.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
```


```{r merge1, include=FALSE}
merge1 <- merge(x = assessments, y = courses, by = c("code_module", "code_presentation"), all.x = TRUE)
```

```{r merge2, include=FALSE}
merge2 <- merge(x = merge1, y = studentassessment, by = "id_assessment", all.x = TRUE)

```

crates a table that groups by code_module, code_presentation, module_presentation_length, id_student and then calculate the final result by summing all the final score calculations of ((weight/100) times score)
does group by selected columns, removes all other columns

```{r newtable2, echo=TRUE}
newtable2 <- merge2 %>%
  group_by( code_module, code_presentation, module_presentation_length, id_student) %>%
  summarise(final_result = (sum(final_score = ((weight / 100) * score))))
  newtable2 <- newtable2[!(newtable2$final_result=="0"),]
 
 newtable2$id_student <- NULL
newtable2<-  newtable2[complete.cases(newtable2), ]
 
newtable2$code_module <- as.factor(newtable2$code_module)
newtable2$code_presentation <- as.factor(newtable2$code_presentation)
newtable2$module_presentation_length <- as.factor(newtable2$module_presentation_length)
newtable2$final_result <- as.factor(newtable2$final_result)
 
```
```{r}
str(newtable2)

```

``` {r}
rules <- apriori(newtable2, parameter = list(support = 0.02, confidence = 0.15))

rules <- sort(rules, by = "lift", decreasing = T) #sorts the rules "by" can be changed
#sort the rules by:
#if "support" is used the lhs doesnt have anything in it
#if "confidence" is used the lhs is length
#if "lift" is used the lhs is module and presentation mainly
length(rules)
inspect(rules[1:5])
```

sort the rules by support and show the top ones (5 ,head) . then test and train in next sprint
