---
title: "Untitled"
output: html_document
---
```{r setup, include=FALSE }
library(ggplot2)
library(plyr)
library(dplyr)
library(arules)
library(arulesViz)
library(tidyverse)
library(rsample)
library(caret)
```


```{r echo=TRUE}
c<- read.csv("data/courses.csv",header=TRUE,sep=",",stringsAsFactors = TRUE)
a<- read.csv("data/assessments.csv",header=TRUE,sep=",",stringsAsFactors = TRUE)
s<- read.csv("data/studentAssessment.csv",header=TRUE,sep=",",stringsAsFactors = TRUE)
## read the data from the scv
m1<-merge(c,a ,by=c("code_module","code_presentation"))%>%merge(s,by="id_assessment")


##mergy the date as one data set 
m2 <- m1 %>%
  group_by( assessment_type, module_presentation_length, code_module, score)

##group the new data set by assessment_type, module_presentation_length, code_module, score
m2$date_submitted <- NULL
m2$is_banked <- NULL
m2$date <- NULL
m2$id_student <- NULL
m2$weight <- NULL
m2 <- m2[complete.cases(m2), ]
```
##remove the several value that do not need 
```{r echo=TRUE}
m2$assessment_type<-as.factor(m2$assessment_type)
m2$module_presentation_length<-as.factor(m2$module_presentation_length)
m2$code_module<-as.factor(m2$code_module)
m2$score<-as.factor(m2$score)
```
```{r echo=TRUE}
## make the assessment_type,module_presentation_length,code_module and score to the factory of the dataset 
rules <- apriori(m2, parameter = list(support = 0.2, confidence = 0.15))

subRules <- which(colSums(is.subset(rules, rules)) > 1) # get subset rules in a vector
length(subRules)
#rules <- rules[-subRules] # remove subset rules
rules_sup <- sort (rules, by="confidence", decreasing = T) # sort by confidence ,and 
inspect(rules_sup) # print top 5 rules


## Analysis
##in this part we try to find the relationship between the score and the assessment_type, module_presentation_length and code_module, as we can see 
## the left predeict the right
## some do not have value can predict  the soce ,some code_module can determing the id_assessment  and some id_assessment can also deteming  some coode_module but not all of them
##several scorfe can determing the assessment _type ,some module_presentation_length can determing the assessment_type =TMA,
#so we get the conclusion some code_module can determing the id_assessment ,and this id assessment can determing part assessment_type ,and this kind of assessment-type can determing the score [0,71],but we can also see even some lhs do not have anything can also determing the score [0,71]
## so in the support = 0.2, confidence = 0.15,it actually do not have any relationship bewteen score and assessment _type ,some module_presentation_length

```