---
title: "sprint2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
```

```{r echo=TRUE}
studentVle <- read.csv("Data/studentVle.csv", header = TRUE, sep =",", stringsAsFactors = TRUE)

summary(studentVle)

```


```{r echo=TRUE}

###The packages employed are ggplot2, dplyr. Dplyr's filter function has helped in selecting one course module that I was working on. The graph produced showed some interesting results for course DDD. The trend for clicks on VLE genereally increased when the semester started (all 4 semesters). There seems to be a spike in all four cases. At the end of the course length, we can also observe an increase in student interactions with the VLE, however, not as much as at the start.  

course <- filter(studentVle, code_module == 'DDD')

Vle <- course %>% group_by(course$date, course$code_presentation, add = FALSE) %>% tally(sum_click)

ggplot(Vle) + geom_line(aes(x=Vle$`course$date`, y =Vle$n, colour = 'red')) + xlim(-24,270) + scale_x_continuous(breaks = seq(-30, 270, by = 20))  + 
  theme(axis.text.x = element_text(size = 12, angle = 90, hjust = 1)) + 
  facet_wrap(~ Vle$`course$code_presentation`, scales = "free_y") +  labs(title = "Analysis for course DDD", x="Date", y="Sum of VLE clicks")

```